### ISSUE TITLE
ensure_indexes seems to make things slower

### ISSUE THREAD

**Issue by kschroeder** [colinmollenhour/Cm_Cache_Backend_Mongo#3]
One of the tests I've done on this shows that the default setting for ensure_indexes makes general load significantly slower during certain remove() operations.  Following is a chart from a single-threaded load test that simulates reads and writes at about a 10:1 ratio.
![Mongo with ensure_index turned on](http://content.screencast.com/users/KevinSchroeder/folders/Jing/media/85a526d4-af55-4006-a85b-ea2e5b704833/2015-02-25_1635.png)

If I turn ensure_index off the response times are much improved. (note the Y axis)

![Mongo with ensure_index turned off](http://content.screencast.com/users/KevinSchroeder/folders/Jing/media/8fa5b63d-cfad-4fdb-89e8-5bcd102fdce8/2015-02-25_1628.png)

Obviously this is a simple configuration item to note but it would probably make sense to make the least prohibitive option the default.

**Comment by colinmollenhour** [comment]
So perhaps the readme should say "should disable after indexes exist" instead of "can disable after indexes exist"?

If ensure_indexes is disabled by default then how would the indexes ever be created? I'm open to ideas.

**Comment by kschroeder** [comment]
That's the odd thing.  Completely disabling the indexes actually made my testing faster overall, including when cleaning by tags.  I don't have the info in front of me, but I think that for inserts it was somewhere between a factor of 5 and 10.  It was pretty significant.  The cost of building the indexes seemed to be much higher than the benefit.

**Comment by colinmollenhour** [comment]
Yes, the id already has an index so lookups are not affected. However, the index on the expiration is required for proper automatic expiration. The index on tags could be omitted, but I think as the dataset grows it would get to the point that this index is more useful. I would venture to guess that this tipping point is probably when the full dataset will no longer fit in memory.

Thanks for sharing your results. I'm interested in more details. Perhaps it would be beneficial to split "ensure_index" into "ensure_tags_index" and "ensure_expiration_index"?

Now I'm thinking the three spikes in your graph must correspond to when the Mongo automatic expiration thread was running. That's pretty terrible performance... I think an external script doing expiration is probably not going to be any faster so I'm guessing the tags index is the performance killer since it is the "largest".

**Comment by kschroeder** [comment]
it could be the expiration thread.  There was a direct correlation between those spikes and error messages like this in the Mongo log "key seems to have moved in the index, refinding".

The testing I did was with 100k keys.  I will try with 1M and 100k tags and see what happens.

**Comment by colinmollenhour** [comment]
That message means index data changed between cursor reads and the cursor has to then be reinitialized. I wouldn't think single document reads would involve a cursor at all.. I'm not a Mongo expert though so not really sure how to proceed but it sounds like this "refinding" is probably happening many times in succession and causing those huge spikes in the graph.

Nice graphs btw, what is your testing methodology?

**Comment by colinmollenhour** [comment]
Can you repeat the tests without the tags index and separately without the expiration index to narrow down for sure which index is related to the problem?

**Comment by kschroeder** [comment]
My research indicates that it's a normal condition for Mongo.  Some times in the logs were showing 30 seconds for an individual insert.  But normal or not, it's prohibitive as a cache (which goes away when turning off the caches).  I intend to do more research on why that's occurring when I get a chance.

The graphs are from JMeter.  I built out a test scenario that replicated how the EE full page cache interacted with the cache.  But populating the FPC on my hardware was an exercise in boredom so I created the script to simulate it without the block rendering and DB access.

**Comment by kschroeder** [comment]
Testing results.  Tags are the problem.  Also found out that if you can't fit the data in memory then performance tanks too.  And data tends to get big fast.  So big that with 16GB of free space on my testing VM I was ran out of disk space when testing 1 million items.  In the end I needed to test what my VM would allow for which was 100k keys with 10k tags with 500 tags per key.  Results are as follows.

Running with
* Keys: 100000
* Tags: 10000
* Clean Size: 10000
* Tags per key: 500

**No indexes**
Populating: Elapsed entry time: 281.62239694595
Read (each key once): 24.826602935791
Cleaning...
Clean run: 10000 tags
Elapsed: 3.1221940517426

**Timeout index**
Populating: Elapsed entry time: 265.46500921249 (This was a 5% variance that could be explained by it running on a VM)
Read (each key once): 24.904706954956
Cleaning...
Clean run: 10000 tags
Elapsed: 4.7567911148071

**Timeout plus tag indexes**
Populating: Elapsed entry time: 1032.5121240616
Read (each key once): 25.044803857803
Cleaning...
Clean run: 10000 tags
Elapsed: 2365.7841200829

Tag indexes caused significant slowdowns both for population and for cleaning.

**Comment by colinmollenhour** [comment]
Is 500 tags per key realistic? I think if you really have 500 tags per key then you're probably not using tags right. I suggest inspecting a production database to get an accurate number as the number of tags per key will significantly impact the indexing performance. Also things like cardinality might affect performance so if you're testing with random keys vs actual keys it might make a difference. The [magento-cache-benchmark](https://github.com/colinmollenhour/magento-cache-benchmark) repo includes a utility to analyze your production cache with one single command:

    $ php shell/cache-benchmark.php analyze

Also in case you weren't aware of it, it makes for a pretty good backend comparison tool as well. :)

Regardless that is certainly disappointing that it suffers so badly even in that scenario but to put things into perspective I think populating keys with 500 tags in Redis would probably not work too great either.

**Comment by kschroeder** [comment]
The 500 keys was actually a true usage scenario.  It's unlikely but I wanted to test a worst case scenario with indexes.  200 is more typical and the effect is still there.  The similar scenario in Redis took 90 seconds in total, compared to the 3 without indexes.

**Comment by colinmollenhour** [comment]
Thanks for the update. I still don't get how you legitimately need 200 tags per key, but it sounds like the performance without the tags index is very good still. So I think a good solution for now would be to have "ensure_tags_index" and "ensure_expiration_index" as separate configs and leave the "ensure_tags_index" off by default. What do you think?

**Comment by colinmollenhour** [comment]
Apparently this performance issue with multi-key (array) indexes is well known: http://codyaray.com/2014/11/mongo-multi-key-index-performance

However, cardinality does play a role as I suspected so if your test uses unique tags for every cache item then your cardinality is much higher than it should be in the real world. E.g. 200 tags * 100K keys = 20MM unique values vs say 20K unique tags that you may have in the real world. If in the real world you really do have more tags than you do keys then it is just poor use of tags in the application.

**Comment by kschroeder** [comment]
The Full Page Cache tags cached pages with any entity that is on the page.  So if you are rendering 200 categories (not unusual for the top nav) then an individual product page will be tagged at least 200 times.

Separating the tags index makes sense.

**Comment by colinmollenhour** [comment]
I am not familiar with EE FPC but if there is a way to hook into an event perhaps and filter tags then that might be worthwhile. E.g. remove all CATEGORY_X tags and replace them with the CATEGORY tag which is cleared on every category save would be more or less the same invalidation behavior. Or remove them entirely and manually clear the FPC as needed since this probably hurts cache hit rate significantly. Seems like a lot easier way to improve performance than beefing up the backend to support an overzealous tagging system.

Thanks again for running the tests and sharing your findings!
